name: Linters

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: python -m pip install flake8
      - name: flake8
        # Pinned to v3.0.0.
        uses: liskin/gh-problem-matcher-wrap@7c16c71e03425eca07dcec470004be43eef74f53
        with:
          linters: flake8
          run: flake8

  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: python -m pip install isort
      - name: isort
        # Pinned to v3.0.0.
        uses: liskin/gh-problem-matcher-wrap@7c16c71e03425eca07dcec470004be43eef74f53
        with:
          linters: isort
          run: isort --check --diff django tests scripts

  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: black
        uses: psf/black@stable
